baseurl = "https://aihumanityclass.github.io/"
languageCode = "en-us"
title = "AI and Humanity"
subtitle = "UVA CS 4501 Spring 2026"
copyright = ""
theme = "aihum"

pageNotFoundTitle = "Not Found"
pageNotFoundDetail = "Your request cannot be resolved in the current axiomatic system. This could be because you have discovered a contradiction to Cantor's Continuum Hypothesis, but it is most likely a bad link or mistyped URL. If its a broken link, please let us know."

[pagination]
pagerSize = 10
path = "page"

[markup.goldmark.renderer]
unsafe= true

[permalinks]
    post = "/:slug/"
    code = "/:slug/"

[taxonomies]
    tag = "tags"
    topic = "topics"

[author]
    name = "UVA TOC"
    #    email = "evans@virginia.edu"

[params]
    brand = "humAnIty"
    topline = "AI and Humanity"
    footline = "<p align=\"center\">CS 4501 | University of Virginia, Spring 2026 | <a href=\"https://www.cs.virginia.edu/evans\">David Evans</a></p>"
    sidebar = "left"
    nodate = true
    noauthor = true
    noread = true
    nopaging=true
    notoc=true

[blackfriday]
    angledQuotes = false
    fractions = false
    hrefTargetBlank = false
    latexDashes = true
    plainIdAnchors = true
    extensions = []
    extensionmask = []

[[menu.footer]]

